/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Venue } from "@prisma/client";

export class VenueServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.VenueCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.VenueCountArgs>
  ): Promise<number> {
    return this.prisma.venue.count(args);
  }

  async venues<T extends Prisma.VenueFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.VenueFindManyArgs>
  ): Promise<Venue[]> {
    return this.prisma.venue.findMany(args);
  }
  async venue<T extends Prisma.VenueFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.VenueFindUniqueArgs>
  ): Promise<Venue | null> {
    return this.prisma.venue.findUnique(args);
  }
  async createVenue<T extends Prisma.VenueCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.VenueCreateArgs>
  ): Promise<Venue> {
    return this.prisma.venue.create<T>(args);
  }
  async updateVenue<T extends Prisma.VenueUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.VenueUpdateArgs>
  ): Promise<Venue> {
    return this.prisma.venue.update<T>(args);
  }
  async deleteVenue<T extends Prisma.VenueDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.VenueDeleteArgs>
  ): Promise<Venue> {
    return this.prisma.venue.delete(args);
  }
}
