/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Promotion as PrismaPromotion,
  Booking as PrismaBooking,
} from "@prisma/client";

export class PromotionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PromotionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.promotion.count(args);
  }

  async promotions<T extends Prisma.PromotionFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.PromotionFindManyArgs>
  ): Promise<PrismaPromotion[]> {
    return this.prisma.promotion.findMany<Prisma.PromotionFindManyArgs>(args);
  }
  async promotion<T extends Prisma.PromotionFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PromotionFindUniqueArgs>
  ): Promise<PrismaPromotion | null> {
    return this.prisma.promotion.findUnique(args);
  }
  async createPromotion<T extends Prisma.PromotionCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PromotionCreateArgs>
  ): Promise<PrismaPromotion> {
    return this.prisma.promotion.create<T>(args);
  }
  async updatePromotion<T extends Prisma.PromotionUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PromotionUpdateArgs>
  ): Promise<PrismaPromotion> {
    return this.prisma.promotion.update<T>(args);
  }
  async deletePromotion<T extends Prisma.PromotionDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.PromotionDeleteArgs>
  ): Promise<PrismaPromotion> {
    return this.prisma.promotion.delete(args);
  }

  async getBooking(parentId: string): Promise<PrismaBooking | null> {
    return this.prisma.promotion
      .findUnique({
        where: { id: parentId },
      })
      .booking();
  }
}
